on:
  workflow_dispatch:

name: freebsd.yaml

jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-hub/actions/setup-r-freebsd@main

      - name: Test R in FreeBSD VM
        run: |
          getRversion()
          R.version[["platform"]]
          .libPaths()
          .Library
          Sys.getenv("R_LIBS_SITE")
          Sys.getenv("R_LIBS_USER")
          find.package("pak")
          Sys.getenv()
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          cache-version: freebsd-1
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          upload-results: never
          upload-snapshots: false
        env:
          NOT_CRAN: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: 'check-results'
          path: check
