on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'OpenBSD release'
        required: true
        type: choice
        options:
        - '7.6'
        - '7.5'
        - '7.4'
        default: '7.6'

name: openbsd.yaml

jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-hub/actions/setup-r-openbsd@v1
        with:
          release: ${{ github.event.inputs.release || '7.6' }}
      - uses: r-hub/actions/platform-info@v1

      - name: Install system packages
        run: |
          pkg_add -I libbind
          cd /usr/local/lib && ln -s libbind/libbind.so* .
        shell: openbsd {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
